version: "2.1"
services:
  server:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
    environment:
        - SCOPE=prod
        - DB_URL=jdbc:mysql://mysql:3306/card_cost?createDatabaseIfNotExist=true&serverTimezone=UTC
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_NAME=card_cost
        - DB_USER=root
        - DB_PASSWORD=
  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 20
    ports:
      - "3307:3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "card_cost"
        MYSQL_PASSWORD: ""
    privileged: true
    volumes:
      - ./mysql_data:/var/lib/mysql